### ISSUE TITLE
significado nome colunas

### ISSUE THREAD

**Issue by eduardomoraes** [victorpasson/pri-turno-eleicoes-2022-pres#1]
Ola Victor,
Muito legal esse trabalho, parabens

Uma pergunta, voce sabe o significado dos nomes das colunas?

**Comment by victorpasson** [comment]
Ei, Eduardo. Muito obrigado.

No site do TSE temos as descrições das colunas em diversos documentos, deixo aqui para consulta:
https://www.tse.jus.br/eleicoes/eleicoes-2022/interessados-na-divulgacao-de-resultados-2022

No site também há diversas informações sobre a obtenção dos arquivos, dá para obter coisas bem mais detalhadas como as eleições para deputados e senadores.

**Comment by eduardomoraes** [comment]
Sensacional, tava me matando procurando essas tabelas com o significado das colunas. Vlw pela info!
